# Kustomize base configuration
# Common resources for all environments

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Resources to include (no namespace here!)
resources:
  - deployment.yaml
  - service.yaml

# Common labels (using new syntax)
labels:
  - pairs:
      app: flask-gitops
      managed-by: kustomize

# Common annotations
commonAnnotations:
  project: "flask-gitops-demo"
  documentation: "https://github.com/mohsensinior117/flask-gitops-app"
