# Production environment kustomization
# Maximum stability and performance

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: flask-app-production

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/service-patch.yaml

labels:
  - pairs:
      environment: production
      tier: production
      criticality: high

namePrefix: prod-

images:
  - name: ghcr.io/mohsensinior117/flask-gitops-app
    newTag: latest
